import { CAREERS, type QuizQuestion } from "./scoring";

// Large question bank per career, used for randomized mock generation
const QUESTION_BANK: Record<string, Array<Omit<QuizQuestion, "id">>> = {
  "Software Developer": [
    { careerTitle: "Software Developer", skill: "JavaScript", type: "fill-blank", text: "Complete the code to declare a constant array:", codeSnippet: "______ colors = ['red', 'blue'];", blankAnswer: "const", options: [{ label: "const", isCorrect: true }, { label: "var", isCorrect: false }, { label: "let", isCorrect: false }, { label: "def", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "JavaScript", type: "mcq", text: "What does Array.prototype.map() return?", options: [{ label: "A new array", isCorrect: true }, { label: "undefined", isCorrect: false }, { label: "The original array", isCorrect: false }, { label: "A boolean", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Debugging", type: "mcq", text: "Which tool is used to set breakpoints in browser?", options: [{ label: "DevTools Debugger", isCorrect: true }, { label: "Terminal", isCorrect: false }, { label: "Notepad", isCorrect: false }, { label: "File Explorer", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Problem-solving", type: "mcq", text: "What data structure uses FIFO ordering?", options: [{ label: "Queue", isCorrect: true }, { label: "Stack", isCorrect: false }, { label: "Tree", isCorrect: false }, { label: "Graph", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "JavaScript", type: "fill-blank", text: "Complete the arrow function syntax:", codeSnippet: "const add = (a, b) ______ a + b;", blankAnswer: "=>", options: [{ label: "=>", isCorrect: true }, { label: "->", isCorrect: false }, { label: "::", isCorrect: false }, { label: "==", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Coding", type: "mcq", text: "Which HTTP method is used to update a resource?", options: [{ label: "PUT", isCorrect: true }, { label: "GET", isCorrect: false }, { label: "DELETE", isCorrect: false }, { label: "HEAD", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "JavaScript", type: "fill-blank", text: "Complete the loop to iterate over an array:", codeSnippet: "for (let i = 0; i ______ arr.length; i++) {}", blankAnswer: "<", options: [{ label: "<", isCorrect: true }, { label: ">", isCorrect: false }, { label: "==", isCorrect: false }, { label: "!=", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Debugging", type: "mcq", text: "What does a 404 HTTP status code mean?", options: [{ label: "Not Found", isCorrect: true }, { label: "Server Error", isCorrect: false }, { label: "Unauthorized", isCorrect: false }, { label: "Success", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Problem-solving", type: "mcq", text: "What is the time complexity of binary search?", options: [{ label: "O(log n)", isCorrect: true }, { label: "O(n)", isCorrect: false }, { label: "O(n²)", isCorrect: false }, { label: "O(1)", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Coding", type: "fill-blank", text: "Complete the function declaration:", codeSnippet: "______ greet(name) { return `Hello ${name}`; }", blankAnswer: "function", options: [{ label: "function", isCorrect: true }, { label: "def", isCorrect: false }, { label: "func", isCorrect: false }, { label: "method", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "JavaScript", type: "mcq", text: "Which method converts JSON string to an object?", options: [{ label: "JSON.parse()", isCorrect: true }, { label: "JSON.stringify()", isCorrect: false }, { label: "JSON.convert()", isCorrect: false }, { label: "JSON.decode()", isCorrect: false }] },
    { careerTitle: "Software Developer", skill: "Debugging", type: "mcq", text: "What does 'NaN' stand for in JavaScript?", options: [{ label: "Not a Number", isCorrect: true }, { label: "No assigned name", isCorrect: false }, { label: "Null and None", isCorrect: false }, { label: "Negative and Null", isCorrect: false }] },
  ],
  "Data Analyst": [
    { careerTitle: "Data Analyst", skill: "SQL", type: "fill-blank", text: "Complete the SQL query to select all rows:", codeSnippet: "SELECT * ______ employees;", blankAnswer: "FROM", options: [{ label: "FROM", isCorrect: true }, { label: "IN", isCorrect: false }, { label: "AT", isCorrect: false }, { label: "OF", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "Excel", type: "mcq", text: "Which Excel function finds the average of a range?", options: [{ label: "AVERAGE()", isCorrect: true }, { label: "MEAN()", isCorrect: false }, { label: "AVG()", isCorrect: false }, { label: "MEDIAN()", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "SQL", type: "mcq", text: "Which SQL clause filters grouped results?", options: [{ label: "HAVING", isCorrect: true }, { label: "WHERE", isCorrect: false }, { label: "FILTER", isCorrect: false }, { label: "GROUP", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "Problem-solving", type: "mcq", text: "What chart type is best for showing trends over time?", options: [{ label: "Line chart", isCorrect: true }, { label: "Pie chart", isCorrect: false }, { label: "Bar chart", isCorrect: false }, { label: "Scatter plot", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "SQL", type: "fill-blank", text: "Complete the query to sort results descending:", codeSnippet: "SELECT name FROM users ORDER BY name ______;", blankAnswer: "DESC", options: [{ label: "DESC", isCorrect: true }, { label: "ASC", isCorrect: false }, { label: "DOWN", isCorrect: false }, { label: "REVERSE", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "Excel", type: "mcq", text: "What does VLOOKUP stand for?", options: [{ label: "Vertical Lookup", isCorrect: true }, { label: "Value Lookup", isCorrect: false }, { label: "Variable Lookup", isCorrect: false }, { label: "Visual Lookup", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "SQL", type: "fill-blank", text: "Complete the JOIN clause:", codeSnippet: "SELECT * FROM orders ______ JOIN customers ON orders.cid = customers.id;", blankAnswer: "INNER", options: [{ label: "INNER", isCorrect: true }, { label: "OUTER", isCorrect: false }, { label: "CROSS", isCorrect: false }, { label: "SELF", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "Problem-solving", type: "mcq", text: "What is a 'null hypothesis' in data analysis?", options: [{ label: "Assumption of no effect", isCorrect: true }, { label: "A missing value", isCorrect: false }, { label: "An empty dataset", isCorrect: false }, { label: "A zero result", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "Excel", type: "fill-blank", text: "Complete the Excel formula to count non-empty cells:", codeSnippet: "=______(A1:A10)", blankAnswer: "COUNTA", options: [{ label: "COUNTA", isCorrect: true }, { label: "COUNT", isCorrect: false }, { label: "SUM", isCorrect: false }, { label: "LEN", isCorrect: false }] },
    { careerTitle: "Data Analyst", skill: "SQL", type: "mcq", text: "Which SQL keyword removes duplicate rows?", options: [{ label: "DISTINCT", isCorrect: true }, { label: "UNIQUE", isCorrect: false }, { label: "DIFFERENT", isCorrect: false }, { label: "SEPARATE", isCorrect: false }] },
  ],
  "Cybersecurity Analyst": [
    { careerTitle: "Cybersecurity Analyst", skill: "Networking", type: "mcq", text: "What port does HTTPS use by default?", options: [{ label: "443", isCorrect: true }, { label: "80", isCorrect: false }, { label: "22", isCorrect: false }, { label: "8080", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Risk Analysis", type: "mcq", text: "What does 'phishing' refer to?", options: [{ label: "Deceptive emails to steal info", isCorrect: true }, { label: "A type of firewall", isCorrect: false }, { label: "Network scanning", isCorrect: false }, { label: "Data encryption", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Networking", type: "fill-blank", text: "Complete the command to check network connectivity:", codeSnippet: "______ google.com", blankAnswer: "ping", options: [{ label: "ping", isCorrect: true }, { label: "send", isCorrect: false }, { label: "check", isCorrect: false }, { label: "test", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Problem-solving", type: "mcq", text: "What is a 'zero-day' vulnerability?", options: [{ label: "An unknown unpatched flaw", isCorrect: true }, { label: "A virus from day one", isCorrect: false }, { label: "A fixed bug", isCorrect: false }, { label: "A test exploit", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Risk Analysis", type: "mcq", text: "What does a firewall primarily do?", options: [{ label: "Filters network traffic", isCorrect: true }, { label: "Encrypts files", isCorrect: false }, { label: "Backs up data", isCorrect: false }, { label: "Scans for viruses", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Networking", type: "mcq", text: "What does DNS stand for?", options: [{ label: "Domain Name System", isCorrect: true }, { label: "Data Network Service", isCorrect: false }, { label: "Direct Node System", isCorrect: false }, { label: "Digital Name Server", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Problem-solving", type: "mcq", text: "What type of attack floods a server with requests?", options: [{ label: "DDoS", isCorrect: true }, { label: "Phishing", isCorrect: false }, { label: "SQL Injection", isCorrect: false }, { label: "Keylogging", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Networking", type: "fill-blank", text: "Complete the protocol for secure shell access:", codeSnippet: "______ user@server.com", blankAnswer: "ssh", options: [{ label: "ssh", isCorrect: true }, { label: "ftp", isCorrect: false }, { label: "http", isCorrect: false }, { label: "telnet", isCorrect: false }] },
    { careerTitle: "Cybersecurity Analyst", skill: "Risk Analysis", type: "mcq", text: "What is the principle of least privilege?", options: [{ label: "Give minimum access needed", isCorrect: true }, { label: "Block all access", isCorrect: false }, { label: "Give admin to everyone", isCorrect: false }, { label: "Rotate passwords daily", isCorrect: false }] },
  ],
  "Accountant": [
    { careerTitle: "Accountant", skill: "Numbers", type: "mcq", text: "Which financial statement shows a company's profitability?", options: [{ label: "Income Statement", isCorrect: true }, { label: "Balance Sheet", isCorrect: false }, { label: "Cash Flow Statement", isCorrect: false }, { label: "Equity Statement", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Analytical Thinking", type: "mcq", text: "What is the accounting equation?", options: [{ label: "Assets = Liabilities + Equity", isCorrect: true }, { label: "Revenue - Expenses = Profit", isCorrect: false }, { label: "Assets = Revenue + Equity", isCorrect: false }, { label: "Liabilities = Assets - Revenue", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Attention to Detail", type: "fill-blank", text: "Complete the journal entry for a cash sale:", codeSnippet: "Debit: Cash\nCredit: ______", blankAnswer: "Revenue", options: [{ label: "Revenue", isCorrect: true }, { label: "Expenses", isCorrect: false }, { label: "Assets", isCorrect: false }, { label: "Liabilities", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Numbers", type: "mcq", text: "If expenses increase, net income:", options: [{ label: "Decreases", isCorrect: true }, { label: "Increases", isCorrect: false }, { label: "Stays the same", isCorrect: false }, { label: "Doubles", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Analytical Thinking", type: "mcq", text: "What does 'depreciation' represent?", options: [{ label: "Asset value decrease over time", isCorrect: true }, { label: "Increase in liability", isCorrect: false }, { label: "Revenue growth", isCorrect: false }, { label: "Tax payment", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Attention to Detail", type: "fill-blank", text: "Complete: Total Assets = Total Liabilities + ______", codeSnippet: "Total Assets = Total Liabilities + ______", blankAnswer: "Owner's Equity", options: [{ label: "Owner's Equity", isCorrect: true }, { label: "Revenue", isCorrect: false }, { label: "Net Income", isCorrect: false }, { label: "Cash", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Numbers", type: "mcq", text: "Which account type normally has a debit balance?", options: [{ label: "Assets", isCorrect: true }, { label: "Revenue", isCorrect: false }, { label: "Liabilities", isCorrect: false }, { label: "Equity", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Analytical Thinking", type: "mcq", text: "What is a 'trial balance' used for?", options: [{ label: "Verify debits equal credits", isCorrect: true }, { label: "Calculate taxes", isCorrect: false }, { label: "Record transactions", isCorrect: false }, { label: "Issue invoices", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Numbers", type: "fill-blank", text: "Complete: Gross Profit = Revenue - ______", codeSnippet: "Gross Profit = Revenue - ______", blankAnswer: "Cost of Goods Sold", options: [{ label: "Cost of Goods Sold", isCorrect: true }, { label: "Tax", isCorrect: false }, { label: "Depreciation", isCorrect: false }, { label: "Interest", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Attention to Detail", type: "mcq", text: "In double-entry bookkeeping, every transaction affects:", options: [{ label: "At least two accounts", isCorrect: true }, { label: "Only one account", isCorrect: false }, { label: "Three accounts", isCorrect: false }, { label: "The cash account only", isCorrect: false }] },
    { careerTitle: "Accountant", skill: "Analytical Thinking", type: "mcq", text: "What does 'accrual accounting' record?", options: [{ label: "Revenue when earned, not received", isCorrect: true }, { label: "Only cash transactions", isCorrect: false }, { label: "Future predictions", isCorrect: false }, { label: "Tax obligations only", isCorrect: false }] },
  ],
  // Healthcare
  "Nurse": [
    { careerTitle: "Nurse", skill: "Patient Care", type: "mcq", text: "What is the normal adult resting heart rate range?", options: [{ label: "60-100 bpm", isCorrect: true }, { label: "40-60 bpm", isCorrect: false }, { label: "100-140 bpm", isCorrect: false }, { label: "30-50 bpm", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Medical Knowledge", type: "mcq", text: "Which vital sign measures body temperature?", options: [{ label: "Temperature", isCorrect: true }, { label: "Pulse", isCorrect: false }, { label: "Blood pressure", isCorrect: false }, { label: "Respiration", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Critical Thinking", type: "mcq", text: "A patient's oxygen saturation drops to 88%. What is the priority action?", options: [{ label: "Administer supplemental oxygen", isCorrect: true }, { label: "Document the reading", isCorrect: false }, { label: "Recheck in one hour", isCorrect: false }, { label: "Offer fluids", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Communication", type: "mcq", text: "What does SBAR stand for in clinical handoffs?", options: [{ label: "Situation, Background, Assessment, Recommendation", isCorrect: true }, { label: "Summary, Background, Action, Review", isCorrect: false }, { label: "Status, Brief, Assess, Report", isCorrect: false }, { label: "Symptoms, Baseline, Analysis, Response", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Patient Care", type: "fill-blank", text: "Complete: The five rights of medication include right patient, drug, dose, route, and right ______.", codeSnippet: "Right patient, drug, dose, route, right ______", blankAnswer: "time", options: [{ label: "time", isCorrect: true }, { label: "nurse", isCorrect: false }, { label: "form", isCorrect: false }, { label: "chart", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Medical Knowledge", type: "mcq", text: "What is the normal range for adult blood pressure?", options: [{ label: "120/80 mmHg", isCorrect: true }, { label: "140/100 mmHg", isCorrect: false }, { label: "90/50 mmHg", isCorrect: false }, { label: "160/110 mmHg", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Critical Thinking", type: "mcq", text: "Which is the best way to verify a patient's identity?", options: [{ label: "Check two identifiers (name + DOB)", isCorrect: true }, { label: "Ask their room number", isCorrect: false }, { label: "Check the bed label", isCorrect: false }, { label: "Ask a colleague", isCorrect: false }] },
    { careerTitle: "Nurse", skill: "Patient Care", type: "mcq", text: "How often should immobile patients be repositioned?", options: [{ label: "Every 2 hours", isCorrect: true }, { label: "Every 6 hours", isCorrect: false }, { label: "Once per shift", isCorrect: false }, { label: "Only when requested", isCorrect: false }] },
  ],
  "Medical Lab Technologist": [
    { careerTitle: "Medical Lab Technologist", skill: "Lab Techniques", type: "mcq", text: "Which tube color is used for coagulation tests?", options: [{ label: "Light blue", isCorrect: true }, { label: "Red", isCorrect: false }, { label: "Green", isCorrect: false }, { label: "Purple", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Analytical Thinking", type: "mcq", text: "What does a hemoglobin test measure?", options: [{ label: "Oxygen-carrying protein in red blood cells", isCorrect: true }, { label: "White blood cell count", isCorrect: false }, { label: "Platelet count", isCorrect: false }, { label: "Blood sugar level", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Attention to Detail", type: "mcq", text: "Why must blood samples be labeled at the bedside?", options: [{ label: "To prevent mislabeling errors", isCorrect: true }, { label: "To save time", isCorrect: false }, { label: "For billing purposes", isCorrect: false }, { label: "It is not required", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Biology", type: "mcq", text: "Which blood type is the universal donor?", options: [{ label: "O negative", isCorrect: true }, { label: "A positive", isCorrect: false }, { label: "AB positive", isCorrect: false }, { label: "B negative", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Lab Techniques", type: "fill-blank", text: "A centrifuge separates blood components based on ______.", codeSnippet: "Centrifuge separates by ______.", blankAnswer: "density", options: [{ label: "density", isCorrect: true }, { label: "color", isCorrect: false }, { label: "temperature", isCorrect: false }, { label: "volume", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Biology", type: "mcq", text: "What organelle is the 'powerhouse of the cell'?", options: [{ label: "Mitochondria", isCorrect: true }, { label: "Nucleus", isCorrect: false }, { label: "Ribosome", isCorrect: false }, { label: "Golgi apparatus", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Analytical Thinking", type: "mcq", text: "What does an elevated WBC count typically indicate?", options: [{ label: "Infection or inflammation", isCorrect: true }, { label: "Dehydration", isCorrect: false }, { label: "Low iron", isCorrect: false }, { label: "High cholesterol", isCorrect: false }] },
    { careerTitle: "Medical Lab Technologist", skill: "Attention to Detail", type: "mcq", text: "What is quality control in a lab used for?", options: [{ label: "Ensuring accuracy of test results", isCorrect: true }, { label: "Cleaning equipment", isCorrect: false }, { label: "Ordering supplies", isCorrect: false }, { label: "Training staff", isCorrect: false }] },
  ],
  "Psychologist": [
    { careerTitle: "Psychologist", skill: "Empathy", type: "mcq", text: "What is 'active listening' in therapy?", options: [{ label: "Fully concentrating and reflecting back", isCorrect: true }, { label: "Taking notes silently", isCorrect: false }, { label: "Asking rapid questions", isCorrect: false }, { label: "Giving advice immediately", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Communication", type: "mcq", text: "What does 'rapport' mean in therapy?", options: [{ label: "A trusting therapist-client relationship", isCorrect: true }, { label: "A diagnostic tool", isCorrect: false }, { label: "A treatment plan", isCorrect: false }, { label: "A billing term", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Research", type: "mcq", text: "What is a 'control group'?", options: [{ label: "The group not receiving treatment", isCorrect: true }, { label: "The group with extra treatment", isCorrect: false }, { label: "The researchers", isCorrect: false }, { label: "The largest group", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Critical Thinking", type: "mcq", text: "Which therapy focuses on changing negative thought patterns?", options: [{ label: "Cognitive Behavioral Therapy (CBT)", isCorrect: true }, { label: "Psychoanalysis", isCorrect: false }, { label: "Art therapy", isCorrect: false }, { label: "Hypnotherapy", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Empathy", type: "mcq", text: "What is 'unconditional positive regard'?", options: [{ label: "Accepting a client without judgment", isCorrect: true }, { label: "Always agreeing", isCorrect: false }, { label: "Giving only positive feedback", isCorrect: false }, { label: "Ignoring negatives", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Research", type: "fill-blank", text: "A p-value less than ______ is typically significant.", codeSnippet: "p < ______", blankAnswer: "0.05", options: [{ label: "0.05", isCorrect: true }, { label: "0.5", isCorrect: false }, { label: "1.0", isCorrect: false }, { label: "0.10", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Communication", type: "mcq", text: "What does 'informed consent' ensure?", options: [{ label: "Client understands and agrees to participate", isCorrect: true }, { label: "Therapist gets paid", isCorrect: false }, { label: "Sessions are recorded", isCorrect: false }, { label: "Insurance is verified", isCorrect: false }] },
    { careerTitle: "Psychologist", skill: "Critical Thinking", type: "mcq", text: "What is 'confirmation bias'?", options: [{ label: "Favoring info that confirms existing beliefs", isCorrect: true }, { label: "Confirming a diagnosis", isCorrect: false }, { label: "A type of memory", isCorrect: false }, { label: "A statistical method", isCorrect: false }] },
  ],
  // Creative
  "UI/UX Designer": [
    { careerTitle: "UI/UX Designer", skill: "Design Thinking", type: "mcq", text: "What is the first stage of Design Thinking?", options: [{ label: "Empathize", isCorrect: true }, { label: "Prototype", isCorrect: false }, { label: "Test", isCorrect: false }, { label: "Define", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "Figma", type: "mcq", text: "What is a 'component' in Figma?", options: [{ label: "A reusable design element", isCorrect: true }, { label: "A page layout", isCorrect: false }, { label: "An export format", isCorrect: false }, { label: "A collaboration feature", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "User Research", type: "mcq", text: "What is a 'user persona'?", options: [{ label: "A fictional representation of a target user", isCorrect: true }, { label: "A real user's profile", isCorrect: false }, { label: "A login screen", isCorrect: false }, { label: "A design template", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "Prototyping", type: "mcq", text: "What differentiates low-fi from high-fi prototypes?", options: [{ label: "Low-fi is sketches; high-fi is detailed/interactive", isCorrect: true }, { label: "They are the same", isCorrect: false }, { label: "Low-fi uses code", isCorrect: false }, { label: "High-fi is always printed", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "Design Thinking", type: "fill-blank", text: "Complete: Empathize, Define, Ideate, Prototype, ______.", codeSnippet: "Empathize → Define → Ideate → Prototype → ______", blankAnswer: "Test", options: [{ label: "Test", isCorrect: true }, { label: "Ship", isCorrect: false }, { label: "Review", isCorrect: false }, { label: "Launch", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "Figma", type: "mcq", text: "What is 'auto layout' in Figma?", options: [{ label: "Automatically adjusts spacing and sizing", isCorrect: true }, { label: "An animation tool", isCorrect: false }, { label: "A color picker", isCorrect: false }, { label: "A plugin", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "User Research", type: "mcq", text: "What is a usability test?", options: [{ label: "Observing users interacting with your product", isCorrect: true }, { label: "Testing code for bugs", isCorrect: false }, { label: "A design review", isCorrect: false }, { label: "A/B testing colors", isCorrect: false }] },
    { careerTitle: "UI/UX Designer", skill: "Prototyping", type: "mcq", text: "Which tool is commonly used for interactive prototypes?", options: [{ label: "Figma", isCorrect: true }, { label: "Excel", isCorrect: false }, { label: "PowerPoint", isCorrect: false }, { label: "Notepad", isCorrect: false }] },
  ],
  "Graphic Designer": [
    { careerTitle: "Graphic Designer", skill: "Visual Design", type: "mcq", text: "What is the 'rule of thirds'?", options: [{ label: "Dividing the frame into a 3×3 grid for balance", isCorrect: true }, { label: "Using only three colors", isCorrect: false }, { label: "Three elements per page", isCorrect: false }, { label: "Three revision rounds", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Typography", type: "mcq", text: "What is 'kerning'?", options: [{ label: "Adjusting space between letter pairs", isCorrect: true }, { label: "Changing font size", isCorrect: false }, { label: "Making text bold", isCorrect: false }, { label: "Center-aligning text", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Color Theory", type: "mcq", text: "Which are primary colors in traditional theory?", options: [{ label: "Red, yellow, blue", isCorrect: true }, { label: "Red, green, blue", isCorrect: false }, { label: "Cyan, magenta, yellow", isCorrect: false }, { label: "Orange, purple, green", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Adobe Tools", type: "mcq", text: "Which Adobe app is best for vector art?", options: [{ label: "Adobe Illustrator", isCorrect: true }, { label: "Adobe Photoshop", isCorrect: false }, { label: "Adobe Premiere", isCorrect: false }, { label: "Adobe Audition", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Color Theory", type: "fill-blank", text: "Complementary colors are opposite on the color ______.", codeSnippet: "Opposite on the color ______.", blankAnswer: "wheel", options: [{ label: "wheel", isCorrect: true }, { label: "spectrum", isCorrect: false }, { label: "chart", isCorrect: false }, { label: "palette", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Visual Design", type: "mcq", text: "What is 'white space' in design?", options: [{ label: "Empty space giving elements room to breathe", isCorrect: true }, { label: "The color white", isCorrect: false }, { label: "Background images", isCorrect: false }, { label: "Text areas", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Typography", type: "mcq", text: "What is a 'serif' font?", options: [{ label: "A font with small strokes at letter ends", isCorrect: true }, { label: "A font without strokes", isCorrect: false }, { label: "A handwritten font", isCorrect: false }, { label: "A monospaced font", isCorrect: false }] },
    { careerTitle: "Graphic Designer", skill: "Adobe Tools", type: "mcq", text: "Which file format supports transparency?", options: [{ label: "PNG", isCorrect: true }, { label: "JPEG", isCorrect: false }, { label: "BMP", isCorrect: false }, { label: "TIFF", isCorrect: false }] },
  ],
  "Content Creator": [
    { careerTitle: "Content Creator", skill: "Writing", type: "mcq", text: "What is a 'call to action' (CTA)?", options: [{ label: "A prompt encouraging the audience to act", isCorrect: true }, { label: "A type of headline", isCorrect: false }, { label: "A content calendar", isCorrect: false }, { label: "A video technique", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "Social Media", type: "mcq", text: "What does 'engagement rate' measure?", options: [{ label: "Interactions relative to reach", isCorrect: true }, { label: "Number of followers", isCorrect: false }, { label: "Post frequency", isCorrect: false }, { label: "Video length", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "Storytelling", type: "mcq", text: "What is the 'hook' in content?", options: [{ label: "The opening that grabs attention", isCorrect: true }, { label: "The conclusion", isCorrect: false }, { label: "A hashtag strategy", isCorrect: false }, { label: "A thumbnail design", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "SEO", type: "mcq", text: "What does SEO stand for?", options: [{ label: "Search Engine Optimization", isCorrect: true }, { label: "Social Engagement Online", isCorrect: false }, { label: "Site Enhancement Operations", isCorrect: false }, { label: "Search Entry Output", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "SEO", type: "fill-blank", text: "The most important HTML heading tag is ______.", codeSnippet: "<______>Title</h1>", blankAnswer: "h1", options: [{ label: "h1", isCorrect: true }, { label: "h6", isCorrect: false }, { label: "title", isCorrect: false }, { label: "header", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "Writing", type: "mcq", text: "What is 'evergreen content'?", options: [{ label: "Content that stays relevant long-term", isCorrect: true }, { label: "Seasonal content", isCorrect: false }, { label: "News articles", isCorrect: false }, { label: "Viral content", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "Social Media", type: "mcq", text: "What makes a social post perform well?", options: [{ label: "Short, concise, visually appealing", isCorrect: true }, { label: "As long as possible", isCorrect: false }, { label: "Only text, no images", isCorrect: false }, { label: "Posting once a month", isCorrect: false }] },
    { careerTitle: "Content Creator", skill: "Storytelling", type: "mcq", text: "What structure uses Setup, Conflict, Resolution?", options: [{ label: "Three-act structure", isCorrect: true }, { label: "AIDA model", isCorrect: false }, { label: "Inverted pyramid", isCorrect: false }, { label: "SCAMPER", isCorrect: false }] },
  ],
  // Business
  "Digital Marketer": [
    { careerTitle: "Digital Marketer", skill: "SEO", type: "mcq", text: "What is a 'backlink'?", options: [{ label: "A link from another site to yours", isCorrect: true }, { label: "A broken link", isCorrect: false }, { label: "An internal link", isCorrect: false }, { label: "A social share", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "Social Media", type: "mcq", text: "What is 'organic reach'?", options: [{ label: "People who see content without paid promotion", isCorrect: true }, { label: "Paid advertising reach", isCorrect: false }, { label: "Bot-generated views", isCorrect: false }, { label: "Email subscribers", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "Analytics", type: "mcq", text: "What does 'bounce rate' measure?", options: [{ label: "Visitors who leave after one page", isCorrect: true }, { label: "Email open rate", isCorrect: false }, { label: "Social unfollows", isCorrect: false }, { label: "Page load speed", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "Copywriting", type: "mcq", text: "What does AIDA stand for?", options: [{ label: "Attention, Interest, Desire, Action", isCorrect: true }, { label: "Awareness, Impact, Decision, Attempt", isCorrect: false }, { label: "Analysis, Insight, Data, Action", isCorrect: false }, { label: "Attention, Insight, Demand, Acquire", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "SEO", type: "fill-blank", text: "The HTML tag for page title in search is ______.", codeSnippet: "<______>My Page</title>", blankAnswer: "title", options: [{ label: "title", isCorrect: true }, { label: "h1", isCorrect: false }, { label: "meta", isCorrect: false }, { label: "head", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "Analytics", type: "mcq", text: "What is a 'conversion rate'?", options: [{ label: "% of visitors completing a desired action", isCorrect: true }, { label: "Number of page views", isCorrect: false }, { label: "Email click rate", isCorrect: false }, { label: "Ad spend efficiency", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "Social Media", type: "mcq", text: "What is A/B testing?", options: [{ label: "Comparing two versions to find which performs better", isCorrect: true }, { label: "Testing on platforms A and B", isCorrect: false }, { label: "A grading system", isCorrect: false }, { label: "Alternating schedules", isCorrect: false }] },
    { careerTitle: "Digital Marketer", skill: "Copywriting", type: "mcq", text: "What makes a good headline?", options: [{ label: "Clear, benefit-driven, creates curiosity", isCorrect: true }, { label: "As long as possible", isCorrect: false }, { label: "ALL CAPS", isCorrect: false }, { label: "Technical jargon", isCorrect: false }] },
  ],
  "Business Analyst": [
    { careerTitle: "Business Analyst", skill: "Data Analysis", type: "mcq", text: "What is a KPI?", options: [{ label: "Key Performance Indicator", isCorrect: true }, { label: "Knowledge Processing Index", isCorrect: false }, { label: "Key Project Input", isCorrect: false }, { label: "Known Problem Identifier", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Problem-solving", type: "mcq", text: "What is SWOT analysis?", options: [{ label: "Strengths, Weaknesses, Opportunities, Threats", isCorrect: true }, { label: "A financial report", isCorrect: false }, { label: "A project timeline", isCorrect: false }, { label: "A coding framework", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Communication", type: "mcq", text: "What is a 'stakeholder'?", options: [{ label: "Anyone with interest in the project", isCorrect: true }, { label: "Only the CEO", isCorrect: false }, { label: "Project manager only", isCorrect: false }, { label: "External customers only", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Excel", type: "mcq", text: "Which Excel function looks up values in a table?", options: [{ label: "VLOOKUP", isCorrect: true }, { label: "CONCATENATE", isCorrect: false }, { label: "SUMPRODUCT", isCorrect: false }, { label: "TRIM", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Excel", type: "fill-blank", text: "Complete: =______(A1:A10, \">100\")", codeSnippet: "=______(A1:A10, \">100\")", blankAnswer: "COUNTIF", options: [{ label: "COUNTIF", isCorrect: true }, { label: "COUNT", isCorrect: false }, { label: "SUMIF", isCorrect: false }, { label: "FILTER", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Data Analysis", type: "mcq", text: "What is a 'user story' in Agile?", options: [{ label: "A feature described from user's perspective", isCorrect: true }, { label: "A bug report", isCorrect: false }, { label: "A database schema", isCorrect: false }, { label: "A test case", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Problem-solving", type: "mcq", text: "What is root cause analysis?", options: [{ label: "Finding the underlying cause of a problem", isCorrect: true }, { label: "Fixing symptoms quickly", isCorrect: false }, { label: "A financial audit", isCorrect: false }, { label: "A hiring process", isCorrect: false }] },
    { careerTitle: "Business Analyst", skill: "Communication", type: "mcq", text: "What is a requirements document?", options: [{ label: "A list of what a system should do", isCorrect: true }, { label: "A code file", isCorrect: false }, { label: "A budget report", isCorrect: false }, { label: "A meeting agenda", isCorrect: false }] },
  ],
  "Entrepreneur": [
    { careerTitle: "Entrepreneur", skill: "Leadership", type: "mcq", text: "What is a 'minimum viable product' (MVP)?", options: [{ label: "Simplest version to test an idea", isCorrect: true }, { label: "The final product", isCorrect: false }, { label: "A marketing strategy", isCorrect: false }, { label: "A team structure", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Risk-taking", type: "mcq", text: "What is 'bootstrapping'?", options: [{ label: "Self-funding without external investors", isCorrect: true }, { label: "Using government grants", isCorrect: false }, { label: "Hiring contractors", isCorrect: false }, { label: "A coding technique", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Financial Literacy", type: "mcq", text: "Revenue vs profit?", options: [{ label: "Revenue is total income; profit is revenue minus expenses", isCorrect: true }, { label: "They are the same", isCorrect: false }, { label: "Profit is always higher", isCorrect: false }, { label: "Revenue only counts cash", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Communication", type: "mcq", text: "What is an 'elevator pitch'?", options: [{ label: "A brief persuasive summary of your idea", isCorrect: true }, { label: "A formal business plan", isCorrect: false }, { label: "A sales contract", isCorrect: false }, { label: "An investor meeting", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Financial Literacy", type: "fill-blank", text: "Profit = Revenue - ______.", codeSnippet: "Profit = Revenue - ______", blankAnswer: "Expenses", options: [{ label: "Expenses", isCorrect: true }, { label: "Tax", isCorrect: false }, { label: "Revenue", isCorrect: false }, { label: "Equity", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Leadership", type: "mcq", text: "What is 'delegation'?", options: [{ label: "Assigning tasks based on strengths", isCorrect: true }, { label: "Doing everything yourself", isCorrect: false }, { label: "Avoiding responsibility", isCorrect: false }, { label: "Hiring more people", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Risk-taking", type: "mcq", text: "What is 'market validation'?", options: [{ label: "Testing if real demand exists", isCorrect: true }, { label: "Registering a trademark", isCorrect: false }, { label: "Setting a price", isCorrect: false }, { label: "Building a website", isCorrect: false }] },
    { careerTitle: "Entrepreneur", skill: "Communication", type: "mcq", text: "What is a 'value proposition'?", options: [{ label: "Why customers should choose your product", isCorrect: true }, { label: "A pricing strategy", isCorrect: false }, { label: "A mission statement", isCorrect: false }, { label: "A financial forecast", isCorrect: false }] },
  ],
};

/** Shuffle array in place (Fisher-Yates) */
function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Generate `count` random questions for a domain, avoiding previously used question texts.
 * Options within each question are also shuffled for variety.
 */
export function generateMockQuestions(
  domain: "Tech" | "Accounting" | "Healthcare" | "Creative" | "Business",
  count: number = 5,
  usedTexts: Set<string> = new Set()
): QuizQuestion[] {
  const domainCareers = CAREERS.filter((c) => c.domain === domain).map((c) => c.title);

  // Gather all available questions for the domain
  const pool = domainCareers.flatMap((career) => QUESTION_BANK[career] ?? []);

  // Filter out previously used questions
  const available = pool.filter((q) => !usedTexts.has(q.text));

  // If not enough unique questions, allow reuse from full pool
  const source = available.length >= count ? available : pool;

  const selected = shuffle(source).slice(0, count);

  return selected.map((q, i) => ({
    ...q,
    id: `mock-${Date.now()}-${i}`,
    options: shuffle(q.options), // randomize option order
  }));
}
